//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inv.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinancialHistory
    {
        public long Id { get; set; }
        public int StockCompanyId { get; set; }
        public string AbsPeriod { get; set; }
        public Nullable<decimal> AssetTurns { get; set; }
        public Nullable<decimal> BasicEpsIncl { get; set; }
        public Nullable<decimal> AvgDaysInventory { get; set; }
        public Nullable<decimal> AvgDaysPayable { get; set; }
        public Nullable<decimal> CashConversion { get; set; }
        public Nullable<decimal> CashFinancing { get; set; }
        public Nullable<decimal> CashInvesting { get; set; }
        public Nullable<decimal> CashOperations { get; set; }
        public Nullable<decimal> CommonEquity1YrAnnGrowth { get; set; }
        public Nullable<decimal> CommonStock { get; set; }
        public Nullable<decimal> CurrentRatio { get; set; }
        public Nullable<decimal> DividendsPerShare { get; set; }
        public Nullable<decimal> Ebitda { get; set; }
        public Nullable<decimal> Ebitda1YrAnnGrowth { get; set; }
        public Nullable<decimal> EbitdaInterest { get; set; }
        public Nullable<decimal> EbitdaMargin { get; set; }
        public Nullable<decimal> Eps { get; set; }
        public Nullable<decimal> Eps1YrAnnGrowth { get; set; }
        public string FilingCurrency { get; set; }
        public Nullable<decimal> FilingDate { get; set; }
        public Nullable<decimal> GrossMargin { get; set; }
        public Nullable<decimal> GrossProfit { get; set; }
        public Nullable<decimal> LongTermDebt { get; set; }
        public Nullable<decimal> MinorityInterest { get; set; }
        public Nullable<decimal> NetChange { get; set; }
        public Nullable<decimal> NetIncome { get; set; }
        public Nullable<decimal> NetIncome1YrAnnGrowth { get; set; }
        public Nullable<decimal> NetIncomeMargin { get; set; }
        public Nullable<decimal> NetPpe { get; set; }
        public Nullable<decimal> PayoutRatio { get; set; }
        public Nullable<decimal> PeriodDate { get; set; }
        public Nullable<decimal> PeriodEndDate { get; set; }
        public Nullable<decimal> QuickRatio { get; set; }
        public Nullable<decimal> RetainedEarnings { get; set; }
        public Nullable<decimal> ReturnAssets { get; set; }
        public Nullable<decimal> ReturnCapital { get; set; }
        public Nullable<decimal> ReturnEquity { get; set; }
        public Nullable<decimal> TotalAssets { get; set; }
        public Nullable<decimal> TotalCurrentAssets { get; set; }
        public Nullable<decimal> TotalCurrentLiabily { get; set; }
        public Nullable<decimal> TotalDebtEquity { get; set; }
        public Nullable<decimal> TotalEquity { get; set; }
        public Nullable<decimal> TotalLiability { get; set; }
        public Nullable<decimal> TotalRevenue { get; set; }
        public Nullable<decimal> TotalRev1YrAnnGrowth { get; set; }
        public Nullable<decimal> TotalRev3YrAnnGrowth { get; set; }
        public Nullable<decimal> TotalRev5YrAnnGrowth { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
    }
}
